# Generated by Django 3.0.3 on 2020-06-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telephone_numb',
            field=models.CharField(blank=True, default='-', max_length=12, unique=True),
        ),
    ]
