# Generated by Django 3.0.3 on 2020-06-16 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendlist', '0002_auto_20200616_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_list', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
