# Generated by Django 3.0.3 on 2020-06-18 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermessage', '0003_auto_20200618_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_text', to='usermessage.MessageText'),
        ),
        migrations.AlterField(
            model_name='messagetext',
            name='message_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
