# Generated by Django 3.0.3 on 2020-06-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermessage', '0004_auto_20200618_1352'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set(),
        ),
    ]
