# Generated by Django 3.0.3 on 2020-06-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermessage', '0005_auto_20200618_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('id',)},
        ),
    ]
