# Generated by Django 3.0.3 on 2020-06-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermessage', '0006_auto_20200619_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetext',
            name='message_text',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
